//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha2

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	resourcev1alpha2 "k8s.io/api/resource/v1alpha2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	resourcev1alpha2client "k8s.io/client-go/kubernetes/typed/resource/v1alpha2"
)

// ResourceClaimParametersClusterGetter has a method to return a ResourceClaimParametersClusterInterface.
// A group's cluster client should implement this interface.
type ResourceClaimParametersClusterGetter interface {
	ResourceClaimParameters() ResourceClaimParametersClusterInterface
}

// ResourceClaimParametersClusterInterface can operate on ResourceClaimParameters across all clusters,
// or scope down to one cluster and return a ResourceClaimParametersNamespacer.
type ResourceClaimParametersClusterInterface interface {
	Cluster(logicalcluster.Path) ResourceClaimParametersNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*resourcev1alpha2.ResourceClaimParametersList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type resourceClaimParametersClusterInterface struct {
	clientCache kcpclient.Cache[*resourcev1alpha2client.ResourceV1alpha2Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *resourceClaimParametersClusterInterface) Cluster(clusterPath logicalcluster.Path) ResourceClaimParametersNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &resourceClaimParametersNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all ResourceClaimParameters across all clusters.
func (c *resourceClaimParametersClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*resourcev1alpha2.ResourceClaimParametersList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResourceClaimParameters(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all ResourceClaimParameters across all clusters.
func (c *resourceClaimParametersClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResourceClaimParameters(metav1.NamespaceAll).Watch(ctx, opts)
}

// ResourceClaimParametersNamespacer can scope to objects within a namespace, returning a resourcev1alpha2client.ResourceClaimParametersInterface.
type ResourceClaimParametersNamespacer interface {
	Namespace(string) resourcev1alpha2client.ResourceClaimParametersInterface
}

type resourceClaimParametersNamespacer struct {
	clientCache kcpclient.Cache[*resourcev1alpha2client.ResourceV1alpha2Client]
	clusterPath logicalcluster.Path
}

func (n *resourceClaimParametersNamespacer) Namespace(namespace string) resourcev1alpha2client.ResourceClaimParametersInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).ResourceClaimParameters(namespace)
}
