//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha2

import (
	"net/http"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	resourcev1alpha2 "k8s.io/client-go/kubernetes/typed/resource/v1alpha2"
	"k8s.io/client-go/rest"
)

type ResourceV1alpha2ClusterInterface interface {
	ResourceV1alpha2ClusterScoper
	ResourceClaimsClusterGetter
	PodSchedulingContextsClusterGetter
	ResourceClassesClusterGetter
	ResourceClaimTemplatesClusterGetter
}

type ResourceV1alpha2ClusterScoper interface {
	Cluster(logicalcluster.Path) resourcev1alpha2.ResourceV1alpha2Interface
}

type ResourceV1alpha2ClusterClient struct {
	clientCache kcpclient.Cache[*resourcev1alpha2.ResourceV1alpha2Client]
}

func (c *ResourceV1alpha2ClusterClient) Cluster(clusterPath logicalcluster.Path) resourcev1alpha2.ResourceV1alpha2Interface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}
	return c.clientCache.ClusterOrDie(clusterPath)
}

func (c *ResourceV1alpha2ClusterClient) ResourceClaims() ResourceClaimClusterInterface {
	return &resourceClaimsClusterInterface{clientCache: c.clientCache}
}

func (c *ResourceV1alpha2ClusterClient) PodSchedulingContexts() PodSchedulingContextClusterInterface {
	return &podSchedulingContextsClusterInterface{clientCache: c.clientCache}
}

func (c *ResourceV1alpha2ClusterClient) ResourceClasses() ResourceClassClusterInterface {
	return &resourceClassesClusterInterface{clientCache: c.clientCache}
}

func (c *ResourceV1alpha2ClusterClient) ResourceClaimTemplates() ResourceClaimTemplateClusterInterface {
	return &resourceClaimTemplatesClusterInterface{clientCache: c.clientCache}
}

// NewForConfig creates a new ResourceV1alpha2ClusterClient for the given config.
// NewForConfig is equivalent to NewForConfigAndClient(c, httpClient),
// where httpClient was generated with rest.HTTPClientFor(c).
func NewForConfig(c *rest.Config) (*ResourceV1alpha2ClusterClient, error) {
	client, err := rest.HTTPClientFor(c)
	if err != nil {
		return nil, err
	}
	return NewForConfigAndClient(c, client)
}

// NewForConfigAndClient creates a new ResourceV1alpha2ClusterClient for the given config and http client.
// Note the http client provided takes precedence over the configured transport values.
func NewForConfigAndClient(c *rest.Config, h *http.Client) (*ResourceV1alpha2ClusterClient, error) {
	cache := kcpclient.NewCache(c, h, &kcpclient.Constructor[*resourcev1alpha2.ResourceV1alpha2Client]{
		NewForConfigAndClient: resourcev1alpha2.NewForConfigAndClient,
	})
	if _, err := cache.Cluster(logicalcluster.Name("root").Path()); err != nil {
		return nil, err
	}
	return &ResourceV1alpha2ClusterClient{clientCache: cache}, nil
}

// NewForConfigOrDie creates a new ResourceV1alpha2ClusterClient for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *ResourceV1alpha2ClusterClient {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}
