//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha2

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	resourcev1alpha2 "k8s.io/api/resource/v1alpha2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	resourcev1alpha2client "k8s.io/client-go/kubernetes/typed/resource/v1alpha2"
)

// ResourceClassParametersClusterGetter has a method to return a ResourceClassParametersClusterInterface.
// A group's cluster client should implement this interface.
type ResourceClassParametersClusterGetter interface {
	ResourceClassParameters() ResourceClassParametersClusterInterface
}

// ResourceClassParametersClusterInterface can operate on ResourceClassParameters across all clusters,
// or scope down to one cluster and return a ResourceClassParametersNamespacer.
type ResourceClassParametersClusterInterface interface {
	Cluster(logicalcluster.Path) ResourceClassParametersNamespacer
	List(ctx context.Context, opts metav1.ListOptions) (*resourcev1alpha2.ResourceClassParametersList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type resourceClassParametersClusterInterface struct {
	clientCache kcpclient.Cache[*resourcev1alpha2client.ResourceV1alpha2Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *resourceClassParametersClusterInterface) Cluster(clusterPath logicalcluster.Path) ResourceClassParametersNamespacer {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return &resourceClassParametersNamespacer{clientCache: c.clientCache, clusterPath: clusterPath}
}

// List returns the entire collection of all ResourceClassParameters across all clusters.
func (c *resourceClassParametersClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*resourcev1alpha2.ResourceClassParametersList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResourceClassParameters(metav1.NamespaceAll).List(ctx, opts)
}

// Watch begins to watch all ResourceClassParameters across all clusters.
func (c *resourceClassParametersClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ResourceClassParameters(metav1.NamespaceAll).Watch(ctx, opts)
}

// ResourceClassParametersNamespacer can scope to objects within a namespace, returning a resourcev1alpha2client.ResourceClassParametersInterface.
type ResourceClassParametersNamespacer interface {
	Namespace(string) resourcev1alpha2client.ResourceClassParametersInterface
}

type resourceClassParametersNamespacer struct {
	clientCache kcpclient.Cache[*resourcev1alpha2client.ResourceV1alpha2Client]
	clusterPath logicalcluster.Path
}

func (n *resourceClassParametersNamespacer) Namespace(namespace string) resourcev1alpha2client.ResourceClassParametersInterface {
	return n.clientCache.ClusterOrDie(n.clusterPath).ResourceClassParameters(namespace)
}
