//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	resourcev1alpha1 "k8s.io/api/resource/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	upstreamresourcev1alpha1informers "k8s.io/client-go/informers/resource/v1alpha1"
	upstreamresourcev1alpha1listers "k8s.io/client-go/listers/resource/v1alpha1"
	"k8s.io/client-go/tools/cache"

	"github.com/kcp-dev/client-go/informers/internalinterfaces"
	clientset "github.com/kcp-dev/client-go/kubernetes"
	resourcev1alpha1listers "github.com/kcp-dev/client-go/listers/resource/v1alpha1"
)

// PodSchedulingClusterInformer provides access to a shared informer and lister for
// PodSchedulings.
type PodSchedulingClusterInformer interface {
	Cluster(logicalcluster.Name) upstreamresourcev1alpha1informers.PodSchedulingInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() resourcev1alpha1listers.PodSchedulingClusterLister
}

type podSchedulingClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewPodSchedulingClusterInformer constructs a new informer for PodScheduling type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewPodSchedulingClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredPodSchedulingClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredPodSchedulingClusterInformer constructs a new informer for PodScheduling type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredPodSchedulingClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourceV1alpha1().PodSchedulings().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourceV1alpha1().PodSchedulings().Watch(context.TODO(), options)
			},
		},
		&resourcev1alpha1.PodScheduling{},
		resyncPeriod,
		indexers,
	)
}

func (f *podSchedulingClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredPodSchedulingClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *podSchedulingClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&resourcev1alpha1.PodScheduling{}, f.defaultInformer)
}

func (f *podSchedulingClusterInformer) Lister() resourcev1alpha1listers.PodSchedulingClusterLister {
	return resourcev1alpha1listers.NewPodSchedulingClusterLister(f.Informer().GetIndexer())
}

func (f *podSchedulingClusterInformer) Cluster(clusterName logicalcluster.Name) upstreamresourcev1alpha1informers.PodSchedulingInformer {
	return &podSchedulingInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type podSchedulingInformer struct {
	informer cache.SharedIndexInformer
	lister   upstreamresourcev1alpha1listers.PodSchedulingLister
}

func (f *podSchedulingInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *podSchedulingInformer) Lister() upstreamresourcev1alpha1listers.PodSchedulingLister {
	return f.lister
}
