//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha2

import (
	"context"
	"time"

	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	kcpinformers "github.com/kcp-dev/apimachinery/v2/third_party/informers"
	"github.com/kcp-dev/logicalcluster/v3"

	resourcev1alpha2 "k8s.io/api/resource/v1alpha2"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
	"k8s.io/apimachinery/pkg/watch"
	upstreamresourcev1alpha2informers "k8s.io/client-go/informers/resource/v1alpha2"
	upstreamresourcev1alpha2listers "k8s.io/client-go/listers/resource/v1alpha2"
	"k8s.io/client-go/tools/cache"

	"github.com/kcp-dev/client-go/informers/internalinterfaces"
	clientset "github.com/kcp-dev/client-go/kubernetes"
	resourcev1alpha2listers "github.com/kcp-dev/client-go/listers/resource/v1alpha2"
)

// ResourceClassParametersClusterInformer provides access to a shared informer and lister for
// ResourceClassParameters.
type ResourceClassParametersClusterInformer interface {
	Cluster(logicalcluster.Name) upstreamresourcev1alpha2informers.ResourceClassParametersInformer
	Informer() kcpcache.ScopeableSharedIndexInformer
	Lister() resourcev1alpha2listers.ResourceClassParametersClusterLister
}

type resourceClassParametersClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewResourceClassParametersClusterInformer constructs a new informer for ResourceClassParameters type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewResourceClassParametersClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredResourceClassParametersClusterInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredResourceClassParametersClusterInformer constructs a new informer for ResourceClassParameters type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredResourceClassParametersClusterInformer(client clientset.ClusterInterface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) kcpcache.ScopeableSharedIndexInformer {
	return kcpinformers.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options metav1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourceV1alpha2().ResourceClassParameters().List(context.TODO(), options)
			},
			WatchFunc: func(options metav1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ResourceV1alpha2().ResourceClassParameters().Watch(context.TODO(), options)
			},
		},
		&resourcev1alpha2.ResourceClassParameters{},
		resyncPeriod,
		indexers,
	)
}

func (f *resourceClassParametersClusterInformer) defaultInformer(client clientset.ClusterInterface, resyncPeriod time.Duration) kcpcache.ScopeableSharedIndexInformer {
	return NewFilteredResourceClassParametersClusterInformer(client, resyncPeriod, cache.Indexers{
		kcpcache.ClusterIndexName:             kcpcache.ClusterIndexFunc,
		kcpcache.ClusterAndNamespaceIndexName: kcpcache.ClusterAndNamespaceIndexFunc},
		f.tweakListOptions,
	)
}

func (f *resourceClassParametersClusterInformer) Informer() kcpcache.ScopeableSharedIndexInformer {
	return f.factory.InformerFor(&resourcev1alpha2.ResourceClassParameters{}, f.defaultInformer)
}

func (f *resourceClassParametersClusterInformer) Lister() resourcev1alpha2listers.ResourceClassParametersClusterLister {
	return resourcev1alpha2listers.NewResourceClassParametersClusterLister(f.Informer().GetIndexer())
}

func (f *resourceClassParametersClusterInformer) Cluster(clusterName logicalcluster.Name) upstreamresourcev1alpha2informers.ResourceClassParametersInformer {
	return &resourceClassParametersInformer{
		informer: f.Informer().Cluster(clusterName),
		lister:   f.Lister().Cluster(clusterName),
	}
}

type resourceClassParametersInformer struct {
	informer cache.SharedIndexInformer
	lister   upstreamresourcev1alpha2listers.ResourceClassParametersLister
}

func (f *resourceClassParametersInformer) Informer() cache.SharedIndexInformer {
	return f.informer
}

func (f *resourceClassParametersInformer) Lister() upstreamresourcev1alpha2listers.ResourceClassParametersLister {
	return f.lister
}
