//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1beta1

import (
	kcpcache "github.com/kcp-dev/apimachinery/v2/pkg/cache"
	"github.com/kcp-dev/logicalcluster/v3"

	policyv1beta1 "k8s.io/api/policy/v1beta1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	policyv1beta1listers "k8s.io/client-go/listers/policy/v1beta1"
	"k8s.io/client-go/tools/cache"
)

// PodSecurityPolicyClusterLister can list PodSecurityPolicies across all workspaces, or scope down to a PodSecurityPolicyLister for one workspace.
// All objects returned here must be treated as read-only.
type PodSecurityPolicyClusterLister interface {
	// List lists all PodSecurityPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*policyv1beta1.PodSecurityPolicy, err error)
	// Cluster returns a lister that can list and get PodSecurityPolicies in one workspace.
	Cluster(clusterName logicalcluster.Name) policyv1beta1listers.PodSecurityPolicyLister
	PodSecurityPolicyClusterListerExpansion
}

type podSecurityPolicyClusterLister struct {
	indexer cache.Indexer
}

// NewPodSecurityPolicyClusterLister returns a new PodSecurityPolicyClusterLister.
// We assume that the indexer:
// - is fed by a cross-workspace LIST+WATCH
// - uses kcpcache.MetaClusterNamespaceKeyFunc as the key function
// - has the kcpcache.ClusterIndex as an index
func NewPodSecurityPolicyClusterLister(indexer cache.Indexer) *podSecurityPolicyClusterLister {
	return &podSecurityPolicyClusterLister{indexer: indexer}
}

// List lists all PodSecurityPolicies in the indexer across all workspaces.
func (s *podSecurityPolicyClusterLister) List(selector labels.Selector) (ret []*policyv1beta1.PodSecurityPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*policyv1beta1.PodSecurityPolicy))
	})
	return ret, err
}

// Cluster scopes the lister to one workspace, allowing users to list and get PodSecurityPolicies.
func (s *podSecurityPolicyClusterLister) Cluster(clusterName logicalcluster.Name) policyv1beta1listers.PodSecurityPolicyLister {
	return &podSecurityPolicyLister{indexer: s.indexer, clusterName: clusterName}
}

// podSecurityPolicyLister implements the policyv1beta1listers.PodSecurityPolicyLister interface.
type podSecurityPolicyLister struct {
	indexer     cache.Indexer
	clusterName logicalcluster.Name
}

// List lists all PodSecurityPolicies in the indexer for a workspace.
func (s *podSecurityPolicyLister) List(selector labels.Selector) (ret []*policyv1beta1.PodSecurityPolicy, err error) {
	err = kcpcache.ListAllByCluster(s.indexer, s.clusterName, selector, func(i interface{}) {
		ret = append(ret, i.(*policyv1beta1.PodSecurityPolicy))
	})
	return ret, err
}

// Get retrieves the PodSecurityPolicy from the indexer for a given workspace and name.
func (s *podSecurityPolicyLister) Get(name string) (*policyv1beta1.PodSecurityPolicy, error) {
	key := kcpcache.ToClusterAwareKey(s.clusterName.String(), "", name)
	obj, exists, err := s.indexer.GetByKey(key)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(policyv1beta1.Resource("podsecuritypolicies"), name)
	}
	return obj.(*policyv1beta1.PodSecurityPolicy), nil
}
