//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The KCP Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by kcp code-generator. DO NOT EDIT.

package v1alpha1

import (
	"context"

	kcpclient "github.com/kcp-dev/apimachinery/v2/pkg/client"
	"github.com/kcp-dev/logicalcluster/v3"

	networkingv1alpha1 "k8s.io/api/networking/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/watch"
	networkingv1alpha1client "k8s.io/client-go/kubernetes/typed/networking/v1alpha1"
)

// ClusterCIDRsClusterGetter has a method to return a ClusterCIDRClusterInterface.
// A group's cluster client should implement this interface.
type ClusterCIDRsClusterGetter interface {
	ClusterCIDRs() ClusterCIDRClusterInterface
}

// ClusterCIDRClusterInterface can operate on ClusterCIDRs across all clusters,
// or scope down to one cluster and return a networkingv1alpha1client.ClusterCIDRInterface.
type ClusterCIDRClusterInterface interface {
	Cluster(logicalcluster.Path) networkingv1alpha1client.ClusterCIDRInterface
	List(ctx context.Context, opts metav1.ListOptions) (*networkingv1alpha1.ClusterCIDRList, error)
	Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error)
}

type clusterCIDRsClusterInterface struct {
	clientCache kcpclient.Cache[*networkingv1alpha1client.NetworkingV1alpha1Client]
}

// Cluster scopes the client down to a particular cluster.
func (c *clusterCIDRsClusterInterface) Cluster(clusterPath logicalcluster.Path) networkingv1alpha1client.ClusterCIDRInterface {
	if clusterPath == logicalcluster.Wildcard {
		panic("A specific cluster must be provided when scoping, not the wildcard.")
	}

	return c.clientCache.ClusterOrDie(clusterPath).ClusterCIDRs()
}

// List returns the entire collection of all ClusterCIDRs across all clusters.
func (c *clusterCIDRsClusterInterface) List(ctx context.Context, opts metav1.ListOptions) (*networkingv1alpha1.ClusterCIDRList, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterCIDRs().List(ctx, opts)
}

// Watch begins to watch all ClusterCIDRs across all clusters.
func (c *clusterCIDRsClusterInterface) Watch(ctx context.Context, opts metav1.ListOptions) (watch.Interface, error) {
	return c.clientCache.ClusterOrDie(logicalcluster.Wildcard).ClusterCIDRs().Watch(ctx, opts)
}
